### ISSUE TITLE
Simplify 'Primitive'

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak-hardware#110]
The definition of Primitive has become overly restrictive for primitives that wouldn't naturally be written as `input_shape -> output_shape`. We could

- Return 'Primitive' to simpler definition.
- Move any abstractions we want to keep into locations closer to where those abstractions are used.
- It has been noted that the 'shape' provided by primitive is perhaps useful at circuit input/output, but overly restrictive at the primitive definition.

**Comment by satnam6502** [comment]
As a point of principle, I would like the`Netlist` type to be a sensible type in Haskell i.e. for it to extract nicely. Currently this is not the case which result in the use of `unsafeCoerce` which is problematic for several reasons.

**Comment by blaxill** [comment]
These changes have been made.
