### ISSUE TITLE
Enable module hierarchy extraction 

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak-hardware#240]
Currently, unless a blackbox primitive is explicitly instantiated, extraction is to a single module. This will lead to a lot of duplication in e.g. `unrolled_forward_cipher_flat` from `arrow-examples/Aes/unrolled_opentitan_cipher.v` where there is a deep hierarchy of modules. Haskell execution of writing a netlist file for `unrolled_forward_cipher_flat` currently times out, this might be unrelated, but also could be due to large duplication of sub-expressions.

**Comment by satnam6502** [comment]
I'll work on this to build upon what already exists for instantiating black-box components as used in the pinmix:
```coq
 '(tl_o, reg2hw) <- blackBox pinmux_reg_top_Interface (tl_i, const1) ;;
```
