### ISSUE TITLE
Monad-based AES block top-level definition

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/oak-hardware#242]
Following up on conversation with @satnam6502 :

We've discussed me trying to verify a monad-based version of the AES block, both to have a point of comparison for proof effort and to have a "backup option" in case the performance issues I'm currently running into with arrows aren't solvable. For the first pass at this, I'd want to work on a similar proof to what I'm currently working on in arrow-land, which means some version of the whole AES block defined in terms of its sub-components. It can be specialized to AES-256, and the loop can be either unrolled or not. It's okay to leave the subroutines (key expansion, `mix_columns`, `sub_bytes`, `shift_rows`, `add_round_key`) as `Axiom`s; I don't need to unfold them or inspect them for this proof. It's also okay to leave things at the level of `arrow-examples/Combinators.v` (for instance, vector reversal) as axioms for now. I've been looking at `unrolled_cipher_naive` for the current proof, so something similar to that will provide the best point of comparison in the short-term. However, if it's a lot of effort to implement, it might be better to go with the more updated, stateful version that we'd need eventually anyway.

**Comment by satnam6502** [comment]
Closing this for now via #304 but please do open new issues for further changes or refinements.
