### ISSUE TITLE
Does coqutil get uninstalled/cleaned by make clean in third_party?

### ISSUE THREAD

**Issue by satnam6502** [project-oak/oak-hardware#256]
Does:
```console
$ cd third_party
$ make clean
```
cause `coqutil` to get "cleaned" or "uninstalled"?

**Comment by jadephilipoom** [comment]
Just cleaned. It calls bedrock2's `cleanall` target, which calls coqutil's `clean` target, which only removes Coq build artifacts.

**Comment by blaxill** [comment]
@satnam6502 note that `third_party/coqutil` does not exist anymore as we use the version included directly in `bedrock2`. It might be the case that you still have the old `third_party/coqutil` hanging around.

**Comment by satnam6502** [comment]
Fixed by #257
