### ISSUE TITLE
`make` is very noisy

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/oak-hardware#305]
Sometimes it's hard to tell what's going on because `make` produces so much output. There are three main sources, as far as I can tell:

1. Complaints about files with duplicate names where the names are not fully-qualified (this is pretty bad, because which file gets loaded is [undefined behavior](https://coq.inria.fr/distrib/current/refman/language/core/modules.html#libraries-and-filesystem):
```
*** Warning: in file Cava/Signal.v, 
    required library String matches several files in path
    (found String.v in ../third_party/coq-ext-lib/theories/Data and ../third_party/bedrock2/deps/coqutil/src/coqutil/Datatypes; used the latter)
```
2. Entering and leaving directories (I think there's a `make` option to suppress these):
```
cd cava && make coq
make[1]: Entering directory '/home/jadep/oak-hardware/cava'
make -f Makefile.coq
make[2]: Entering directory '/home/jadep/oak-hardware/cava'
make[3]: Nothing to be done for 'real-all'.
make[2]: Leaving directory '/home/jadep/oak-hardware/cava'
make[1]: Leaving directory '/home/jadep/oak-hardware/cava'
```
3. Extraction-related warnings:
```
File "./Extraction.v", line 64, characters 0-28:
Warning: The following logical axioms were
encountered: aes_sbox_canright_correct BitArithmetic.nat_of_bits_sized_n.
Having
invalid logical axiom in the environment when extracting may lead to
incorrect or non-terminating ML terms.
 [extraction-logical-axiom,extraction]
```

It would be nice to do something about these. Number (3) is a warning we might actually want to pay attention to and continue receiving, but perhaps we can reduce the sheer number of those that are produced or offer a `make quiet` target.

**Comment by satnam6502** [comment]
Agreed. Let's discuss the best strategy for this at the weekly team meeting.
