### ISSUE TITLE
Prove that shift_rows and sub_bytes commute

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/oak-hardware#310]
Related to and partially dependent on #294, related to #309 

Once we have specifications for *both* `shift_rows` and `sub_bytes`, we need to prove that the two operations commute, e.g.:
 ```coq
  forall st, shift_rows (sub_bytes st) = sub_bytes (shift_rows st)
```

**Comment by smore-lore** [comment]
Though will wait to start until:
https://github.com/project-oak/oak-hardware/pull/369
https://github.com/project-oak/oak-hardware/pull/370
