### ISSUE TITLE
Prove that monad-based AES matches spec

### ISSUE THREAD

**Issue by jadephilipoom** [project-oak/oak-hardware#315]
Now that #242 is complete, prove that the implementation there matches the AES specification.

**Comment by satnam6502** [comment]
For make "Acorn-based AES implementation that's closer to OpenTitan", should we mutate this thread of make a parallel spec and implementation?

**Comment by jadephilipoom** [comment]
You mean reopen this issue after the merge closes it and rephrase it? I think instead we should close this issue and make a new one -- the issue as originally described is solved, and the closer-to-OpenTitan version seems to me like a distinct new step.
