### ISSUE TITLE
Reuse Spec AES Test Routines for Arrow / Monad

### ISSUE THREAD

**Issue by blaxill** [project-oak/oak-hardware#356]
Jade has added much more thorough testing for AES which we might be able to reuse for monad/arrow constructions (likely this will be easier for monad than arrow). Of course this is not a blocker.

**Comment by jadephilipoom** [comment]
I think it might actually be pretty quick? All you need is a Gallina function that uses flat vectors, and there are already some helpers for converting to/from flat vectors in the tests. For arrows, I think it would be something like:
```coq
Compute (aes_test_encrypt Hex (fun (step : AESStep) key =>
                                   match step with
                                   | ShiftRows =>
                                       fun st : Vector.t bool 128 =>
                                         let input := map byte_to_bitvec (to_cols st) in
                                         let output := combinational_evaluation arrow_shift_rows input in
                                         from_cols (map bitvec_to_byte output)
                                   | _ => aes_impl step key
                                   end)).
```
I might not have gotten the representation change exactly right there, but something along those lines. For Acorn, should be similar -- all you need is to use the identity monad and peel it off at the end.
```coq
Compute (aes_test_encrypt Hex (fun (step : AESStep) key =>
                                   match step with
                                   | ShiftRows =>
                                       fun st : Vector.t bool 128 =>
                                         let input := map byte_to_bitvec (to_cols st) in
                                         let output := unIdent (acorn_shift_rows input) in
                                         from_cols (map bitvec_to_byte output)
                                   | _ => aes_impl step key
                                   end)).
```
I know it's currently marked as P3, but this might be directly helpful for #320/#321/#322/#323. I might take this one once #354 is merged and just see if I can get it working with a small amount of effort.
