### ISSUE TITLE
Add tuple support to SignalType

### ISSUE THREAD

**Issue by satnam6502** [project-oak/oak-hardware#397]
Allow tuples to be expressed by `SignalType`. This is needed in general to describe circuits and avoid the issue faces in #395 where a composite value is needed (ideally a pair of an 8-bit value and a boolean value) but @jadephilipoom had to instead construct a 9-bit value. We previously accomplished this using the `Shape` type which let us describe internal tupling structure with port-level tuples flattened. However, this stratification was removed as an unnecessary level of complexity but we have not yet "ported" types to the `SignalType`. We should either reject circuits which have top level tuple type ports or make up fresh names for each element (recursively).

**Comment by jadephilipoom** [comment]
I think we should also consider the possibility of using a sigma-type list (i.e. `list {t : SignalType & signal t}`) or an inductive heterogeneous list datatype. It depends how often we need this kind of multiple-input-signal structure; if we need it in a lot of places, then it might well be worth reintroducing the tuple structure at `SignalType` level. But if it's just for loops and maybe a few other places, the list strategy would be a good way to avoid having to reason about arbitrarily nested tuples.
